### ISSUE TITLE
Absolute path to the game

### ISSUE THREAD

**Issue by Zhincore** [rayshader/cp2077-red-cli#1]
Hey,
I don't really fancy putting the absolute path to the game in my config json, I want to push it to my git repository. Is there a way to make red-cli read the path elsewhere? Like a `.env` file or so?
Thanks

**Comment by poirierlouis** [comment]
Hi,

You can push config json without defining "game" key first, and not commit the line with your absolute game path for now.

Thanks for pointing this. What do you think if I read an environment variable, like `REDCLI_GAME` instead? It could fallback like this: detect default path => env var => "game" key in config json.

**Comment by Zhincore** [comment]
Thank you! I like your idea, sounds good to me!
